# This workflow will build the project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: XNote++ build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: cp build.properties.ori build.properties && ant -noinput -buildfile build.xml clean package
    - uses: actions/upload-artifact@v2
      with:
        name: Add-on package
        path: build/*.xpi
